# <center> Digit Recognizer - MNIST Dataset </center>
___

Computer vision is a very important field in data science. From reading of alphabets and numbers to self-driving cars, the computer vision projects have a wide variety of applications.

One of the initial projects of computer vision was <i>Digit Recognition</i> and the dataset used was MNIST ("Modified National Institute of Standards and Technology") dataset. This is like the "Hello World!" of the computer vision. 

This is the classic dataset that has 60,000 handwritten images served for training and validation purpose and 10,000 images for testing purpose. Since its inception in 1999, this has served as the benchmark of classification problems.

I chose <b>Python</b> my preferred language.

## Importing the relevant libraries

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout, Conv2D, MaxPooling2D, BatchNormalization
from sklearn.metrics import accuracy_score

Using TensorFlow backend.


## Importing the **MNIST** dataset from _keras.datasets_

In [2]:
from keras.datasets import mnist
import numpy as np
import pandas as pd

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


## Reshaping input data
It is recommened to declare the the depth of the image data, irrespective of MNIST data having the default depth of 1.

In [0]:
x_train = x_train.reshape(x_train.shape[0], x_train.shape[1], x_train.shape[2], 1)
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1], x_test.shape[2], 1)

In [4]:
x_train.shape, x_test.shape

((60000, 28, 28, 1), (10000, 28, 28, 1))

## Normalizing the input data in the range [0,1].

In [0]:
x_train = x_train.astype('float')/255
x_test = x_test.astype('float')/255

Since there are 10 digits [0-9], there are, hence, 10 different classes (1 class for each digit).

In the MNIST dataset, the are one-dimensional array. Hence, we convert this into 10-dimensional class matrix.

In [0]:
from keras.utils import np_utils

y_train_cat = np_utils.to_categorical(y_train, num_classes=10)
y_test_cat = np_utils.to_categorical(y_test, num_classes=10)

In [7]:
print(y_train_cat, y_test_cat)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]] [[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Creating a neural network

1. Sequential
2. 2D Convolution layer
3. Dropout layer
4. Flatten
5. Dense layers
6. Final Dense (output) layer

In [0]:
model = Sequential()
model.add(Conv2D(filters = 64, kernel_size = 12, input_shape = (28,28,1),  
                 kernel_initializer = 'glorot_normal', activation = 'relu'))
model.add(BatchNormalization())
model.add(Dropout(0.25))
model.add(Conv2D(filters = 32, kernel_size = 8, activation = 'relu'))
model.add(Flatten())
model.add(Dense(32, activation = 'relu'))
model.add(Dense(10, activation = 'softmax')) #Final Output Layer

In [19]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 17, 17, 64)        9280      
_________________________________________________________________
batch_normalization_4 (Batch (None, 17, 17, 64)        256       
_________________________________________________________________
dropout_4 (Dropout)          (None, 17, 17, 64)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 10, 10, 32)        131104    
_________________________________________________________________
flatten_4 (Flatten)          (None, 3200)              0         
_________________________________________________________________
dense_7 (Dense)              (None, 32)                102432    
_________________________________________________________________
dense_8 (Dense)              (None, 10)               

In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train_cat, batch_size = 32, epochs = 10)

Epoch 1/10
60000/60000 [==============================] - 281s 5ms/step - loss: 0.1202 - acc: 0.9668
Epoch 2/10
60000/60000 [==============================] - 281s 5ms/step - loss: 0.0701 - acc: 0.9801
Epoch 3/10
60000/60000 [==============================] - 283s 5ms/step - loss: 0.0521 - acc: 0.9851
Epoch 4/10
60000/60000 [==============================] - 284s 5ms/step - loss: 0.0446 - acc: 0.9872
Epoch 5/10
60000/60000 [==============================] - 282s 5ms/step - loss: 0.0381 - acc: 0.9887
Epoch 6/10
60000/60000 [==============================] - 282s 5ms/step - loss: 0.0354 - acc: 0.9897
Epoch 7/10
60000/60000 [==============================] - 281s 5ms/step - loss: 0.0299 - acc: 0.9913
Epoch 8/10
60000/60000 [==============================] - 282s 5ms/step - loss: 0.0271 - acc: 0.9925
Epoch 9/10
60000/60000 [==============================] - 283s 5ms/step - loss: 0.0261 - acc: 0.9925
Epoch 10/10
60000/60000 [==============================] - 282s 5ms/step - loss: 0.0218 - a

In [24]:
model.evaluate(x_test, y_test_cat)

10000/10000 [==============================] - 10s 1ms/step


[0.05102009525202984, 0.9871]

In [25]:
pred_class = model.predict_classes(x_test)
accuracy_score(y_true = y_test, y_pred = pred_class)

0.9871